import React from 'react'
import '@/app/(screen)/globals.css'
import { Metadata } from 'next';
export const metadata: Metadata = {
    title: "Ecomart",
    description: "Generated by Ammar shaikh",
};
const AuthLayout = ({ children }: { children: React.ReactNode }) => {
    return (
        <html>
            <body suppressHydrationWarning={true}>
                {children}
            </body>
        </html>
    )
}

export default AuthLayout