const shopLeftData = [
    {
        pic: "/left1.png",
        title: "Dictum morbi",
        offerPrice: "$26.00",
        regularPrice: "$52.00",
        review: "/reviews.png",
        des: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Magna in est adipiscing in phasellus non in justo.",
    },
    {
        pic: "/left2.png",
        title: "Sodales sit",
        offerPrice: "$26.00",
        regularPrice: "$52.00",
        review: "/reviews.png",
        des: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Magna in est adipiscing in phasellus non in justo.",
    },
    {
        pic: "/left3.png",
        title: "Nibh varius",
        offerPrice: "$26.00",
        regularPrice: "$52.00",
        review: "/reviews.png",
        des: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Magna in est adipiscing in phasellus non in justo.",
    },
    {
        pic: "/left4.png",
        title: "Mauris quis",
        offerPrice: "$26.00",
        regularPrice: "$52.00",
        review: "/reviews.png",
        des: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Magna in est adipiscing in phasellus non in justo.",
    },
    {
        pic: "/left5.png",
        title: "Morbi sagittis",
        offerPrice: "$26.00",
        regularPrice: "$52.00",
        review: "/reviews.png",
        des: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Magna in est adipiscing in phasellus non in justo.",
    },
    {
        pic: "/left6.png",
        title: "Ultricies venenatis",
        offerPrice: "$26.00",
        regularPrice: "$52.00",
        review: "/reviews.png",
        des: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Magna in est adipiscing in phasellus non in justo.",
    },
    {
        pic: "/left7.png",
        title: "Scelerisque dignissim",
        offerPrice: "$26.00",
        regularPrice: "$52.00",
        review: "/reviews.png",
        des: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Magna in est adipiscing in phasellus non in justo.",
    }, 
]

export default shopLeftData